### ISSUE TITLE
Battery Level wrong, Temperature whacked 

### ISSUE THREAD

**Issue by MTOakey** [gdyr/qsys-plugin-docs#4]
Greetings, LOVE the "QXL-D" version 1 plugin for Qsys, but I just noticed that the "Battery Level" shows 100% {Level 5} when there are NO batteries installed. It does track correctly when batteries are installed - showing depletion Levels 4, 3, 2, 1 correctly... however, when I remove the batteries to replace with fresh ones, the Level jumps back to 100% Level 5 - without any batteries installed yet.
And when batteries are installed - the temperature shows a ridiculous reading of "11335.0 F"
I don't really care about the Temp issue, but it would be nice to see correctly when using "Rechargeables" that get really hot when they are bad.
But I really DO want to see the correct Battery Level of 0% or Level 0/1 when there are NO batteries installed.

Thank You, please let me know if there is anything else I can provide to assist, or if there is anything I can do to help rectify this issue.

Pic shows Mic 1 with fresh batteries, and Mic 2, 3, 4 all without any batteries installed.
And You can see the Temperature also.

![Shure Battery issue](https://github.com/gdyr/qsys-plugin-docs/assets/62364168/d4fb8ae0-1491-48f9-9961-b2d5e91fb633)

.

**Comment by gdyr** [comment]
Hi @MTOakey, this is a plugin example repository, not a support channel for plugins.
You would need to reach out to your Shure representative about this, or QSC, who can contact the plugin developer on your behalf.
